### ISSUE TITLE
livestream error

### ISSUE THREAD

**Issue by liurln** [citolen/goproh4#21]
I've tried to run livestream.js. I had installed ffmpeg. and I still got this error message.

[livestream] started
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

p.s. run on windows 10 aniversary build with node 4.5.0 npm 3.10.6

**Comment by citolen** [comment]
Hi,

Could  you make sure that you are able to run ffmpeg from a command line?

I suspect that the path to ffmpeg isn't correctly set in your PATH variable.

Have a look at this: http://www.wikihow.com/Install-FFmpeg-on-Windows

**Comment by liurln** [comment]
Hello,
Thank you for your response. It was my fault. I forget to add ffmpeg to system's path. I can live stream my gopro now.
