### ISSUE TITLE
livestream fail

### ISSUE THREAD

**Issue by tlkao01** [citolen/goproh4#9]
here is my issue when i try livestream
[livestream] started
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by citolen** [comment]
Hello,

You need to have ffmpeg installed.

Cheers,
Nils
